version: '3.8'

services:
  mysql:
    image: docker.arvancloud.ir/mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
